x-env: &base_env
  - BUNDLE_JOBS=4
  - BUNDLE_PATH=vendor/bundle
  - BUNDLE_BIN=/bundle/bin
  - GEM_HOME=/bundle
  - BUNDLE_FORGET_CLI_OPTIONS=true
  - POSTGRES_DB=courses_development
  - RAILS_ENV=development

services:
  app:
    image: ruby:3.2.2
    entrypoint: /var/courses/docker-entrypoint.sh
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./:/var/courses
    environment: *base_env
    tty: true
    depends_on:
      - database

  database:
    image: postgres:17
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
